function supportstorage(){return"object"==typeof window.localStorage?!0:!1}function handleSaveLayout(){var a=$(".demo").html();stopsave||a==window.demoHtml||(stopsave++,window.demoHtml=a,saveLayout(),stopsave--)}var layouthistory;function saveLayout(){var a=layouthistory;a||(a={count:0,list:[]});if(a.list.length>a.count)for(i=a.count;i<a.list.length;i++)a.list[i]=null;a.list[a.count]=window.demoHtml;a.count++;supportstorage()&&localStorage.setItem("layoutdata",JSON.stringify(a));layouthistory=a}
function downloadLayout(){$.ajax({type:"POST",url:"/build/downloadLayout",data:{layout:$("#download-layout").html()},success:function(a){window.location.href="/build/download"}})}function downloadHtmlLayout(){$.ajax({type:"POST",url:"/build/downloadLayout",data:{layout:$("#download-layout").html()},success:function(a){window.location.href="/build/downloadHtml"}})}
function undoLayout(){var a=layouthistory;if(a){if(2>a.count)return!1;window.demoHtml=a.list[a.count-2];a.count--;$(".demo").html(window.demoHtml);supportstorage()&&localStorage.setItem("layoutdata",JSON.stringify(a));return!0}return!1}function redoLayout(){var a=layouthistory;return a&&a.list[a.count]?(window.demoHtml=a.list[a.count],a.count++,$(".demo").html(window.demoHtml),supportstorage()&&localStorage.setItem("layoutdata",JSON.stringify(a)),!0):!1}
function handleJsIds(){handleModalIds();handleAccordionIds();handleCarouselIds();handleTabsIds()}function handleAccordionIds(){var a=$(".demo #myAccordion"),b="accordion-"+randomNumber(),d;a.attr("id",b);a.find(".accordion-group").each(function(a,c){d="accordion-element-"+randomNumber();$(c).find(".accordion-toggle").each(function(a,e){$(e).attr("data-parent","#"+b);$(e).attr("href","#"+d)});$(c).find(".accordion-body").each(function(a,b){$(b).attr("id",d)})})}
function handleCarouselIds(){var a=$(".demo #myCarousel"),b="carousel-"+randomNumber();a.attr("id",b);a.find(".carousel-indicators li").each(function(a,e){$(e).attr("data-target","#"+b)});a.find(".left").attr("href","#"+b);a.find(".right").attr("href","#"+b)}function handleModalIds(){var a=$(".demo #myModalLink"),b=randomNumber(),d="modal-container-"+b;a.attr("id","modal-"+b);a.attr("href","#"+d);a.next().attr("id",d)}
function handleTabsIds(){var a=$(".demo #myTabs"),b="tabs-"+randomNumber();a.attr("id",b);a.find(".tab-pane").each(function(a,b){var c=$(b).attr("id"),f="panel-"+randomNumber();$(b).attr("id",f);$(b).parent().parent().find("a[href\x3d#"+c+"]").attr("href","#"+f)})}function randomNumber(){return randomFromInterval(1,1E6)}function randomFromInterval(a,b){return Math.floor(Math.random()*(b-a+1)+a)}
function gridSystemGenerator(){$(".lyrow .preview input").bind("keyup",function(){var a=0,b="",d=$(this).val().split(" ",12);$.each(d,function(d,c){a+=parseInt(c);b+='\x3cdiv class\x3d"span'+c+' column"\x3e\x3c/div\x3e'});12==a?($(this).parent().next().children().html(b),$(this).parent().prev().show()):$(this).parent().prev().hide()})}
function configurationElm(a,b){$(".demo").delegate(".configuration \x3e a","click",function(a){a.preventDefault();a=$(this).parent().next().next().children();$(this).toggleClass("active");a.toggleClass($(this).attr("rel"))});$(".demo").delegate(".configuration .dropdown-menu a","click",function(a){a.preventDefault();a=$(this).parent().parent();var b=a.parent().parent().next().next().children();a.find("li").removeClass("active");$(this).parent().addClass("active");var c="";a.find("a").each(function(){c+=
$(this).attr("rel")+" "});a.parent().removeClass("open");b.removeClass(c);b.addClass($(this).attr("rel"))})}function removeElm(){$(".demo").delegate(".remove","click",function(a){a.preventDefault();$(this).parent().remove();0<!$(".demo .lyrow").length&&clearDemo()})}function clearDemo(){$(".demo").empty();layouthistory=null;supportstorage()&&localStorage.removeItem("layoutdata")}function removeMenuClasses(){$("#menu-layoutit li button").removeClass("active")}
function changeStructure(a,b){$("#download-layout ."+a).removeClass(a).addClass(b)}function cleanHtml(a){$(a).parent().append($(a).children().html())}
function downloadLayoutSrc(){$("#download-layout").children().html($(".demo").html());var a=$("#download-layout").children();a.find(".preview, .configuration, .drag, .remove").remove();a.find(".lyrow").addClass("removeClean");a.find(".box-element").addClass("removeClean");a.find(".lyrow .lyrow .lyrow .lyrow .lyrow .removeClean").each(function(){cleanHtml(this)});a.find(".lyrow .lyrow .lyrow .lyrow .removeClean").each(function(){cleanHtml(this)});a.find(".lyrow .lyrow .lyrow .removeClean").each(function(){cleanHtml(this)});
a.find(".lyrow .lyrow .removeClean").each(function(){cleanHtml(this)});a.find(".lyrow .removeClean").each(function(){cleanHtml(this)});a.find(".removeClean").each(function(){cleanHtml(this)});a.find(".removeClean").remove();$("#download-layout .column").removeClass("ui-sortable");$("#download-layout .row-fluid").removeClass("clearfix").children().removeClass("column");0<$("#download-layout .container").length&&changeStructure("row-fluid","row");formatSrc=$.htmlClean($("#download-layout").html(),{format:!0,
allowedAttributes:[["id"],["class"],["data-toggle"],["data-target"],["data-parent"],["role"],["data-dismiss"],["aria-labelledby"],["aria-hidden"],["data-slide-to"],["data-slide"]]});$("#download-layout").html(formatSrc);$("#downloadModal textarea").empty();$("#downloadModal textarea").val(formatSrc)}var currentDocument=null,timerSave=1E3,stopsave=0,startdrag=0,demoHtml=$(".demo").html(),currenteditor=null;
$(window).resize(function(){$("body").css("min-height",$(window).height()-90);$(".demo").css("min-height",$(window).height()-160)});function restoreData(){if(supportstorage()){layouthistory=JSON.parse(localStorage.getItem("layoutdata"));if(!layouthistory)return!1;window.demoHtml=layouthistory.list[layouthistory.count-1];window.demoHtml&&$(".demo").html(window.demoHtml)}}function initContainer(){}
$(document).ready(function(){$("body").css("min-height",$(window).height()-90);$(".demo").css("min-height",$(window).height()-160);$(".sidebar-nav .lyrow").draggable({connectToSortable:".demo",helper:"clone",handle:".drag",start:function(a,b){startdrag||stopsave++;startdrag=1},drag:function(a,b){b.helper.width(400)},stop:function(a,b){$(".demo .column").sortable({opacity:0.35,connectWith:".column",start:function(a,b){startdrag||stopsave++;startdrag=1},stop:function(a,b){0<stopsave&&stopsave--;startdrag=
0}});0<stopsave&&stopsave--;startdrag=0}});$(".sidebar-nav .box").draggable({connectToSortable:".column",helper:"clone",handle:".drag",start:function(a,b){startdrag||stopsave++;startdrag=1},drag:function(a,b){b.helper.width(400)},stop:function(){handleJsIds();0<stopsave&&stopsave--;startdrag=0}});initContainer();$("#savecontent").click(function(a){a.preventDefault();currenteditor.html(contenthandle.getData())});$("[data-target\x3d#downloadModal]").click(function(a){a.preventDefault();downloadLayoutSrc()});
$("[data-target\x3d#shareModal]").click(function(a){a.preventDefault();handleSaveLayout()});$("#download").click(function(){downloadLayout();return!1});$("#downloadhtml").click(function(){downloadHtmlLayout();return!1});$("#edit").click(function(){$("body").removeClass("devpreview sourcepreview");$("body").addClass("edit");removeMenuClasses();$(this).addClass("active");return!1});$("#clear").click(function(a){a.preventDefault();clearDemo()});$("#devpreview").click(function(){$("body").removeClass("edit sourcepreview");
$("body").addClass("devpreview");removeMenuClasses();$(this).addClass("active");return!1});$("#sourcepreview").click(function(){$("body").removeClass("edit");$("body").addClass("devpreview sourcepreview");removeMenuClasses();$(this).addClass("active");return!1});$("#fluidPage").click(function(a){a.preventDefault();changeStructure("container","container-fluid");$("#fixedPage").removeClass("active");$(this).addClass("active");downloadLayoutSrc()});$("#fixedPage").click(function(a){a.preventDefault();
changeStructure("container-fluid","container");$("#fluidPage").removeClass("active");$(this).addClass("active");downloadLayoutSrc()});$(".nav-header").click(function(){$(".sidebar-nav .boxes, .sidebar-nav .rows").hide();$(this).next().slideDown()});$("#undo").click(function(){stopsave++;undoLayout()&&initContainer();stopsave--});$("#redo").click(function(){stopsave++;redoLayout()&&initContainer();stopsave--});removeElm();gridSystemGenerator();setInterval(function(){handleSaveLayout()},timerSave)});